# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyansible < Formula
  desc "A lazy TUI for Ansible — browse inventory, run playbooks, stream logs"
  homepage "https://github.com/kocierik/lazyansible"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.2/lazyansible_1.0.2_darwin_x86_64.tar.gz"
      sha256 "36e114ad0b3a60d8c6e5fb07e92f2cfecb6274d68a3551d3a2c7dbcb5406c14e"

      define_method(:install) do
        bin.install "lazyansible"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.2/lazyansible_1.0.2_darwin_arm64.tar.gz"
      sha256 "b71b6e4319ffcf0c6ddc18a4245dc3810df02323f9dd88eef53241a565588959"

      define_method(:install) do
        bin.install "lazyansible"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.2/lazyansible_1.0.2_linux_x86_64.tar.gz"
      sha256 "a03dd5678ff4681fc46ec86a24c8ab81b7a181e16b917323b114112bac29b6c4"
      define_method(:install) do
        bin.install "lazyansible"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.2/lazyansible_1.0.2_linux_armv6.tar.gz"
      sha256 "76110ae6730370c0df0df662c2b27348e683b127415449ce553d198b5039f170"
      define_method(:install) do
        bin.install "lazyansible"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.2/lazyansible_1.0.2_linux_arm64.tar.gz"
      sha256 "c50385ef768f272b0c84523b13c754517861bd3287de3ed52e647eda0d11c02c"
      define_method(:install) do
        bin.install "lazyansible"
      end
    end
  end

  test do
    system "#{bin}/lazyansible", "--version"
  end
end
