# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyansible < Formula
  desc "A lazy TUI for Ansible — browse inventory, run playbooks, stream logs"
  homepage "https://github.com/kocierik/lazyansible"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.3/lazyansible_1.0.3_darwin_x86_64.tar.gz"
      sha256 "827ef7977217a89c284ec17719ad2f6730e090afe7125eb45657bdbe480a5b8d"

      define_method(:install) do
        bin.install "lazyansible"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.3/lazyansible_1.0.3_darwin_arm64.tar.gz"
      sha256 "d669a5d9f3fe9406b9ea84acc129740d96cb34118b389cc618829ebd2358b658"

      define_method(:install) do
        bin.install "lazyansible"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.3/lazyansible_1.0.3_linux_x86_64.tar.gz"
      sha256 "43a804d6ee82441ccdb7c4ef7fab2abcb06048381838649149fbaf66de0d6f06"
      define_method(:install) do
        bin.install "lazyansible"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.3/lazyansible_1.0.3_linux_armv6.tar.gz"
      sha256 "6e04c70afe760ee8ff3ae0f5791853bf01b86469ac7e29f1b52cd946cee47ca1"
      define_method(:install) do
        bin.install "lazyansible"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kocierik/lazyansible/releases/download/v1.0.3/lazyansible_1.0.3_linux_arm64.tar.gz"
      sha256 "1ca3445481d5398246a3caf9749196ed86760cba23c39cae769a756baad49ccb"
      define_method(:install) do
        bin.install "lazyansible"
      end
    end
  end

  test do
    system "#{bin}/lazyansible", "--version"
  end
end
